/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/__health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État du serveur et de la session BBox */
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentification par login/mot de passe */
        post: operations["AuthController_loginRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Déconnexion — invalide le cookie de session */
        post: operations["AuthController_logoutRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identité de l'utilisateur courant */
        get: operations["AuthController_meRoute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan réseau — flux SSE
         * @description Retourne un flux Server-Sent Events.
         *     - `progress` — `{ done, total }` avancement
         *     - `host` — hôte découvert (ping + MAC + vendor)
         *     - `host-detail` — détails (ports ouverts, mDNS, SMB)
         *     - `done` — fin du scan
         *     - `error` — erreur fatale
         */
        get: operations["ScanController_scan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping continu — flux SSE
         * @description Envoie des pings ICMP en boucle. Événement `ping` émis à chaque cycle :
         *     `{ ip: string, rtt: number | null }[]` — null si l'hôte est injoignable.
         */
        get: operations["PingController_ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Flux SSE d'hôtes réseau agrégés depuis tous les plugins
         * @description Retourne un flux Server-Sent Events.
         *     - `progress` — `{ pct: number, label: string }` avancement
         *     - `result` — `{ hosts: Host[] }` résultat final
         */
        get: operations["HostsController_hosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__map/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Topologie réseau agrégée pour la carte
         * @description Agrège les données Wi-Fi de tous les plugins configurés (bbox, cudy, airport, kuwfi…)
         *     et retourne une structure normalisée. Les hostnames sont résolus côté serveur.
         */
        get: operations["MapController_topology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__check-ip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifie si une IP est joignable et résout son adresse MAC */
        get: operations["CheckIpController_checkIp"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__oui": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Résolution du fabricant depuis les 3 premiers octets d'une adresse MAC */
        get: operations["OuiController_oui"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__config/ui": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration UI (menu latéral, widgets, DHCP) */
        get: operations["RouterConfigController_uiConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__config/routers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste tous les routeurs activés dans config.yaml */
        get: operations["RouterConfigController_routers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/wireless": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clients Wi-Fi connectés à la BBox */
        get: operations["getBboxWireless"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Appareils connectés au réseau local (bbox) */
        get: operations["getBboxHosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Informations sur le routeur BBox (modèle, firmware, uptime…) */
        get: operations["getBboxDevice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/wan/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistiques de trafic WAN instantanées */
        get: operations["getBboxWanStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/wan/graphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historique de débit WAN sur la dernière heure
         * @description Agrège les endpoints Bbox downstream/hour et upstream/hour.
         *     Chaque point contient un timestamp Unix (secondes) et une valeur en kbps.
         */
        get: operations["getBboxWanGraphs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/dhcp/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration du serveur DHCP */
        get: operations["getBboxDhcpConfig"];
        /** Met à jour la configuration DHCP */
        put: operations["updateBboxDhcpConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/dhcp/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des réservations DHCP statiques */
        get: operations["getBboxDhcpClients"];
        put?: never;
        /** Crée une réservation DHCP */
        post: operations["createBboxDhcpClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/dhcp/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Met à jour une réservation DHCP */
        put: operations["updateBboxDhcpClient"];
        post?: never;
        /** Supprime une réservation DHCP */
        delete: operations["deleteBboxDhcpClient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/dhcp/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options DHCP configurées et disponibles */
        get: operations["getBboxDhcpOptions"];
        put?: never;
        /** Crée une option DHCP */
        post: operations["createBboxDhcpOption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/dhcp/options/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Met à jour une option DHCP */
        put: operations["updateBboxDhcpOption"];
        post?: never;
        /** Supprime une option DHCP */
        delete: operations["deleteBboxDhcpOption"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/wifi-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paramètres Wi-Fi (SSID, mot de passe, bande) */
        get: operations["getBboxWifiSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/cudy/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des routeurs Cudy configurés */
        get: operations["getCudyStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/cudy/{routerId}/wireless": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clients Wi-Fi connectés à un AP Cudy */
        get: operations["getCudyWireless"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/cudy/{routerId}/bandwidth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Débit Wi-Fi des interfaces ra0 (2.4 GHz) et rai0 (5 GHz)
         * @description Calcule les débits instantanés par dérivation des volumes cumulatifs.
         *     Valeurs en kbps.
         */
        get: operations["getCudyBandwidth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/cudy/{routerId}/devlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des appareils connectés via LuCI (iface, ip, mac, débit) */
        get: operations["getCudyDevlist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/airport/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des AirPort configurés */
        get: operations["getAirportStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/airport/{routerId}/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hôtes connectés à un AirPort (via table ARP ACP) */
        get: operations["getAirportHosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/airport/{routerId}/wireless": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clients Wi-Fi connectés à un AirPort (données ACP brutes) */
        get: operations["getAirportWireless"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/airport/{routerId}/wifi-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paramètres Wi-Fi de l'AirPort (interfaces ACP) */
        get: operations["getAirportWifiSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/airport/{routerId}/device-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Informations sur l'appareil AirPort (via mDNS/ACP) */
        get: operations["getAirportDeviceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/kuwfi/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des APs KuWFi configurés */
        get: operations["getKuwfiStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/kuwfi/{routerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Données complètes d'un AP KuWFi (accessPoints + clients) */
        get: operations["getKuwfiRouter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/kuwfi/{routerId}/bandwidth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Débit Wi-Fi par bande (2.4 GHz et 5 GHz) en kbps */
        get: operations["getKuwfiBandwidth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/nestwifi-proxy/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des appareils NestWifi configurés */
        get: operations["getNestWifiStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/nestwifi-proxy/{routerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hôtes détectés par un AP NestWifi (via ARP local) */
        get: operations["getNestWifiRouter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            ok: boolean;
            hasSession: boolean;
            /** @example https://mabbox.bytel.fr */
            target: string;
        };
        LoginRequest: {
            /** @example admin */
            username: string;
            /** @example secret */
            password: string;
        };
        LoginResponse: {
            ok: boolean;
            /** @example admin */
            username: string;
        };
        MeResponse: {
            /** @example admin */
            username: string | null;
            authEnabled: boolean;
        };
        MapClient: {
            /** @example AA:BB:CC:DD:EE:FF */
            mac: string;
            hostname?: string;
            /** @example 192.168.1.10 */
            ip?: string;
            /** @example -65 */
            signal_dbm?: number;
        };
        MapAccessPoint: {
            id: string;
            label: string;
            sublabel?: string;
            /** @example bbox-wifi */
            kind: string;
            online: boolean;
            clients: components["schemas"]["MapClient"][];
        };
        MapTopology: {
            accessPoints: components["schemas"]["MapAccessPoint"][];
        };
        CheckIpResponse: {
            reachable: boolean;
            /** @example aa:bb:cc:dd:ee:ff */
            mac: string | null;
        };
        OuiResponse: {
            /** @example Apple, Inc. */
            vendor: string | null;
        };
        UiMenuItem: {
            id: string;
            /** @example bbox-main */
            router?: string;
            children?: components["schemas"]["UiMenuItem"][];
        };
        UiWidget: {
            type: string;
            id: string;
        };
        UiHomeConfig: {
            widgets: components["schemas"]["UiWidget"][];
        };
        UiDhcpConfig: {
            router: string;
        };
        UiConfig: {
            menu: components["schemas"]["UiMenuItem"][] | null;
            home: components["schemas"]["UiHomeConfig"] | null;
            dhcp: components["schemas"]["UiDhcpConfig"] | null;
        };
        RouterEntry: {
            /** @example bbox-main */
            name: string;
            /** @example bbox */
            type: string;
        };
        WirelessClient: {
            /** @example AA:BB:CC:DD:EE:FF */
            mac: string;
            /**
             * @description Signal en dBm (négatif)
             * @example -65
             */
            signal_dbm: number;
            /** @description Débit Tx en kbps */
            tx_kbps: number;
            /** @description Débit Rx en kbps */
            rx_kbps: number;
            /** @description Inactivité en ms */
            inactive_ms: number;
        };
        AccessPoint: {
            ssid: string;
            /** @enum {string} */
            band: "2.4G" | "5G";
            channel: number;
            clients: components["schemas"]["WirelessClient"][];
            bssid?: string;
            password?: string;
            standard?: string;
            width?: number;
        };
        AirportWifiClient: {
            mac: string;
            ip: string;
            hostname: string;
            /** @description RSSI en dBm */
            rssi_dbm: number;
            /** @description Débit Tx en Mbps */
            txrate_mbps: number;
        };
        AirportAccessPoint: {
            ifname: string;
            ssid: string;
            /** @enum {string} */
            band: "2.4G" | "5G";
            channel: number;
            clients: components["schemas"]["AirportWifiClient"][];
        };
        AirportDeviceInfo: {
            /** @description Adresse MAC LAN */
            laMA?: string;
            /** @description Adresse MAC Radio */
            raMA?: string;
            /** @description Adresse MAC WAN */
            waMA?: string;
            features?: string[];
        };
        AirportHost: {
            mac: string;
            ip: string;
            hostname: string;
            wireless: boolean;
        };
        AirportRouterDetail: {
            online: boolean;
            hosts: components["schemas"]["AirportHost"][];
        };
        AirportWifiInterface: {
            ifIndex: number;
            description: string;
            clientCount: number;
        };
        AirportWifiSettings: {
            interfaces: components["schemas"]["AirportWifiInterface"][];
        };
        AirportWirelessData: {
            online: boolean;
            accessPoints: components["schemas"]["AirportAccessPoint"][];
        };
        CudyBandwidthPoint: {
            /** @description Unix timestamp (secondes) */
            ts: number;
            /** @description Débit montant en kbps */
            up: number;
            /** @description Débit descendant en kbps */
            down: number;
        };
        CudyBandwidthData: {
            /** @description Interface 2.4 GHz */
            ra0: components["schemas"]["CudyBandwidthPoint"][];
            /** @description Interface 5 GHz */
            rai0: components["schemas"]["CudyBandwidthPoint"][];
        };
        CudyDevlistEntry: {
            /** @description Nom de l'interface réseau (ex: ra0, eth0) */
            iface: string;
            ip: string;
            mac: string;
            /** @description Débit Tx en kbps */
            tx_kbps: number;
            /** @description Débit Rx en kbps */
            rx_kbps: number;
            signal: string | null;
            /** @description Durée de connexion (ex: 00:01:23) */
            duration: string;
        };
        DeviceUsing: {
            ipv4: boolean;
            ipv6: boolean;
            ftth: boolean;
        };
        DeviceData: {
            modelname: string;
            serialnumber: string;
            firmware: string;
            firmwareDate: string;
            /** @description Uptime en secondes */
            uptime: number;
            boots: number;
            using: components["schemas"]["DeviceUsing"];
        };
        DhcpClient: {
            id: number;
            enable: number;
            hostname: string;
            macaddress: string;
            ipaddress: string;
            ip6address: string;
        };
        DhcpClientWrite: {
            enable: number;
            macaddress: string;
            ipaddress: string;
            ip6address: string;
            hostname: string;
        };
        DhcpClientsData: {
            clients: components["schemas"]["DhcpClient"][];
        };
        DhcpConfig: {
            enable: number;
            /** @example 192.168.1.2 */
            minaddress: string;
            /** @example 192.168.1.254 */
            maxaddress: string;
            /** @description Durée de bail en secondes */
            leasetime: number;
        };
        DhcpConfigData: {
            config: components["schemas"]["DhcpConfig"];
        };
        DhcpConfigUpdate: {
            enable?: number;
            minaddress?: string;
            maxaddress?: string;
            leasetime?: number;
        };
        DhcpOption: {
            id: number;
            option: number;
            value: string;
        };
        DhcpOptionCapability: {
            id: number;
            /** @enum {string} */
            type: "INT" | "IP" | "STRING" | "BOOL";
            description: string;
        };
        DhcpOptionWrite: {
            option: number;
            value: string;
        };
        DhcpOptionsData: {
            options: components["schemas"]["DhcpOption"][];
            optionsstatic: components["schemas"]["DhcpOption"][];
            capabilities: components["schemas"]["DhcpOptionCapability"][];
        };
        Host: {
            /** @example AA:BB:CC:DD:EE:FF */
            mac: string;
            /** @example 192.168.1.10 */
            ip: string;
            ip6?: string;
            hostname: string;
            active: boolean;
            type?: string;
            /** @enum {string} */
            connexion?: "wired" | "wifi 2.4G" | "wifi 5G";
            ssid?: string;
            /** @description Unix timestamp (secondes) */
            lastseen?: number;
        };
        HostDetailEvent: {
            ip: string;
            openPorts: number[];
            mdnsName: string;
            smbName: string;
            smbDomain: string;
        };
        HostsData: {
            hosts: components["schemas"]["Host"][];
        };
        HostsProgressEvent: {
            /** @description Pourcentage d'avancement (0-100) */
            pct: number;
            /** @description Nom du plugin en cours */
            label: string;
        };
        KuwfiClient: {
            mac: string;
            ip: string;
            signal_dbm: number;
            /** @enum {string} */
            band: "2.4G" | "5G";
            ssid: string;
        };
        KuwfiAccessPoint: {
            ssid: string;
            /** @enum {string} */
            band: "2.4G" | "5G";
            channel: number;
            clients: components["schemas"]["KuwfiClient"][];
        };
        KuwfiBandwidthPoint: {
            /** @description Unix timestamp (secondes) */
            ts: number;
            /** @description Débit montant en kbps */
            up: number;
            /** @description Débit descendant en kbps */
            down: number;
        };
        KuwfiBandwidthData: {
            /** @description Bande 2.4 GHz */
            band24: components["schemas"]["KuwfiBandwidthPoint"][];
            /** @description Bande 5 GHz */
            band5: components["schemas"]["KuwfiBandwidthPoint"][];
        };
        KuwfiRouterResult: {
            name: string;
            ip: string;
            online: boolean;
            firmware: string;
            uptime: number;
            accessPoints: components["schemas"]["KuwfiAccessPoint"][];
        };
        NestWifiHost: {
            mac: string;
            ip: string;
            hostname: string;
        };
        NestWifiRouterResult: {
            name: string;
            ip: string;
            online: boolean;
            hosts: components["schemas"]["NestWifiHost"][];
        };
        PingResult: {
            ip: string;
            /** @description RTT en ms, null si injoignable */
            rtt: number | null;
        };
        RouterStatusEntry: {
            name: string;
            ip: string;
        };
        RouterStatusResponse: {
            routers: components["schemas"]["RouterStatusEntry"][];
        };
        ScanHostEvent: {
            ip: string;
            mac: string;
            hostname: string;
            vendor: string;
            ping: boolean;
        };
        ScanProgressEvent: {
            done: number;
            total: number;
        };
        WanGraphPoint: {
            /** @description Unix timestamp (secondes) */
            ts: number;
            /** @description Débit en kbps */
            value: number;
        };
        WanGraphsData: {
            down: components["schemas"]["WanGraphPoint"][];
            up: components["schemas"]["WanGraphPoint"][];
        };
        WanStatsSide: {
            bytes: number;
            bandwidth: number;
            contractualBandwidth: number;
            occupation: number;
        };
        WanStatsData: {
            rx: components["schemas"]["WanStatsSide"];
            tx: components["schemas"]["WanStatsSide"];
        };
        WirelessData: {
            online: boolean;
            accessPoints: components["schemas"]["AccessPoint"][];
        };
    };
    responses: never;
    parameters: {
        routerId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    AuthController_loginRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Corps de requête invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Identifiants incorrects */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logoutRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    AuthController_meRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ScanController_scan: {
        parameters: {
            query?: {
                /** @description CIDR à scanner (ex. 192.168.1.0/24). Détecté automatiquement si absent. */
                subnet?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flux SSE text/event-stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PingController_ping: {
        parameters: {
            query: {
                /** @description Liste d'IP séparées par des virgules */
                ips: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flux SSE text/event-stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Aucune IP fournie */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HostsController_hosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flux SSE text/event-stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MapController_topology: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapTopology"];
                };
            };
        };
    };
    CheckIpController_checkIp: {
        parameters: {
            query: {
                /** @description Adresse IPv4 à tester */
                ip: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckIpResponse"];
                };
            };
            /** @description Format d'IP invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OuiController_oui: {
        parameters: {
            query: {
                /** @description Adresse MAC complète (tous formats acceptés) */
                mac: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OuiResponse"];
                };
            };
            /** @description Paramètre mac manquant ou invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RouterConfigController_uiConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UiConfig"];
                };
            };
        };
    };
    RouterConfigController_routers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouterEntry"][];
                };
            };
        };
    };
    getBboxWireless: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WirelessData"];
                };
            };
        };
    };
    getBboxHosts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostsData"];
                };
            };
        };
    };
    getBboxDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceData"];
                };
            };
        };
    };
    getBboxWanStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WanStatsData"];
                };
            };
        };
    };
    getBboxWanGraphs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WanGraphsData"];
                };
            };
        };
    };
    getBboxDhcpConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DhcpConfigData"];
                };
            };
        };
    };
    updateBboxDhcpConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpConfigUpdate"];
            };
        };
        responses: {
            /** @description OK */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBboxDhcpClients: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DhcpClientsData"];
                };
            };
        };
    };
    createBboxDhcpClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpClientWrite"];
            };
        };
        responses: {
            /** @description Créé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBboxDhcpClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpClientWrite"];
            };
        };
        responses: {
            /** @description OK */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteBboxDhcpClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBboxDhcpOptions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DhcpOptionsData"];
                };
            };
        };
    };
    createBboxDhcpOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpOptionWrite"];
            };
        };
        responses: {
            /** @description Créé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBboxDhcpOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpOptionWrite"];
            };
        };
        responses: {
            /** @description OK */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteBboxDhcpOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBboxWifiSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WirelessData"];
                };
            };
        };
    };
    getCudyStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouterStatusResponse"];
                };
            };
        };
    };
    getCudyWireless: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WirelessData"];
                };
            };
            /** @description Routeur introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCudyBandwidth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CudyBandwidthData"];
                };
            };
            /** @description Routeur introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCudyDevlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CudyDevlistEntry"][];
                };
            };
            /** @description Routeur introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Login LuCI échoué ou endpoint indisponible */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAirportStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouterStatusResponse"];
                };
            };
        };
    };
    getAirportHosts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportRouterDetail"];
                };
            };
            /** @description Routeur introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erreur de communication ACP */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAirportWireless: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportWirelessData"];
                };
            };
            /** @description Routeur introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAirportWifiSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportWifiSettings"];
                };
            };
            /** @description Routeur introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAirportDeviceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportDeviceInfo"];
                };
            };
        };
    };
    getKuwfiStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouterStatusResponse"];
                };
            };
        };
    };
    getKuwfiRouter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KuwfiRouterResult"];
                };
            };
            /** @description Routeur introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getKuwfiBandwidth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KuwfiBandwidthData"];
                };
            };
            /** @description Routeur introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getNestWifiStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouterStatusResponse"];
                };
            };
        };
    };
    getNestWifiRouter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NestWifiRouterResult"];
                };
            };
            /** @description Routeur introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
