/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/__health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État du serveur et de la session BBox */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__check-ip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifie si une IP est joignable et résout son adresse MAC */
        get: operations["checkIp"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Flux SSE de scan réseau
         * @description Retourne un flux Server-Sent Events. Événements émis :
         *     - `progress` — avancement du scan
         *     - `host` — hôte découvert (ping + MAC + vendor)
         *     - `host-detail` — détails d'un hôte (ports, ping stats, mDNS, SMB)
         *     - `done` — fin du scan
         *     - `error` — erreur fatale
         */
        get: operations["scanNetwork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__config/routers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste tous les routeurs configurés (tous types) */
        get: operations["getConfigRouters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__map/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Topologie réseau agrégée pour la carte
         * @description Agrège les données Wi-Fi de tous les plugins configurés (bbox, cudy, etc.)
         *     et retourne une structure normalisée. Les hostnames sont résolus côté serveur.
         */
        get: operations["getMapTopology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/cudy/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des routeurs Cudy configurés */
        get: operations["getCudyStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/cudy/{routerId}/wireless": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clients Wi-Fi connectés à un AP Cudy (contrat commun WirelessData) */
        get: operations["getCudyWireless"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/cudy/{routerId}/bandwidth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Débit Wi-Fi des interfaces ra0 (2.4 GHz) et rai0 (5 GHz)
         * @description Calcule les débits instantanés par dérivation des volumes cumulatifs
         *     retournés par LuCI (/admin/status/bandwidth).
         *     Valeurs en kbps.
         */
        get: operations["getCudyBandwidth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/wireless": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clients Wi-Fi connectés à la BBox (contrat commun WirelessData) */
        get: operations["getBboxWireless"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Appareils connectés au réseau local */
        get: operations["getHosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Informations sur le routeur (modèle, firmware, uptime…) */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/wan/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistiques de trafic WAN instantanées (débit, octets cumulés) */
        get: operations["getWanStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/wan/graphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historique de débit WAN sur la dernière heure
         * @description Agrège les endpoints Bbox /api/v1/graphs/wan/downstream/hour et upstream/hour.
         *     Chaque point contient un timestamp Unix (secondes) et une valeur en kbps.
         *     Le premier point de chaque série est le plus ancien.
         */
        get: operations["getWanGraphs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/dhcp/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration du serveur DHCP */
        get: operations["getDhcpConfig"];
        /** Met à jour la configuration DHCP */
        put: operations["updateDhcpConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/dhcp/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des réservations DHCP statiques */
        get: operations["getDhcpClients"];
        put?: never;
        /** Crée une réservation DHCP */
        post: operations["createDhcpClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/dhcp/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Met à jour une réservation DHCP */
        put: operations["updateDhcpClient"];
        post?: never;
        /** Supprime une réservation DHCP */
        delete: operations["deleteDhcpClient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/dhcp/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options DHCP configurées et disponibles */
        get: operations["getDhcpOptions"];
        put?: never;
        /** Crée une option DHCP */
        post: operations["createDhcpOption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/api-proxy/bbox/{routerId}/dhcp/options/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Met à jour une option DHCP */
        put: operations["updateDhcpOption"];
        post?: never;
        /** Supprime une option DHCP */
        delete: operations["deleteDhcpOption"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RouterEntry: {
            /** @example bbox-main */
            name: string;
            /** @enum {string} */
            type: "bbox" | "cudy";
        };
        MapClient: {
            /** @example AA:BB:CC:DD:EE:FF */
            mac: string;
            /** @example my-device */
            hostname?: string;
            /** @example -65 */
            signal_dbm?: number;
        };
        MapAccessPoint: {
            id: string;
            label: string;
            sublabel?: string;
            /** @example bbox-wifi */
            kind: string;
            online: boolean;
            clients: components["schemas"]["MapClient"][];
        };
        MapTopology: {
            accessPoints: components["schemas"]["MapAccessPoint"][];
        };
        HealthResponse: {
            ok: boolean;
            hasSession: boolean;
            /** @example https://mabbox.bytel.fr */
            target: string;
        };
        CheckIpResponse: {
            reachable: boolean;
            mac: string | null;
        };
        ScanProgress: {
            done: number;
            total: number;
        };
        ScanHost: {
            ip: string;
            mac: string;
            hostname: string;
            vendor: string;
            ping: boolean;
        };
        HostDetail: {
            ip: string;
            pingStats?: null | {
                min: number;
                avg: number;
                max: number;
            };
            openPorts: number[];
            mdnsName: string;
            smbName: string;
            smbDomain: string;
        };
        WirelessClient: {
            mac: string;
            /** @description Signal strength in dBm (negative) */
            signal_dbm: number;
            /** @description Transmit rate in kbps */
            tx_kbps: number;
            /** @description Receive rate in kbps */
            rx_kbps: number;
            /** @description Time since last activity in milliseconds */
            inactive_ms: number;
        };
        AccessPoint: {
            ssid: string;
            /** @enum {string} */
            band: "2.4G" | "5G";
            channel: number;
            clients: components["schemas"]["WirelessClient"][];
        };
        WirelessData: {
            online: boolean;
            accessPoints: components["schemas"]["AccessPoint"][];
        };
        Host: {
            mac: string;
            ip: string;
            ip6?: string;
            hostname: string;
            active: boolean;
            type?: string;
            /** @description Unix timestamp (seconds) */
            lastseen?: number;
        };
        HostsData: {
            hosts: components["schemas"]["Host"][];
        };
        DeviceData: {
            modelname: string;
            serialnumber: string;
            firmware: string;
            firmwareDate: string;
            /** @description Uptime in seconds */
            uptime: number;
            boots: number;
            using: {
                ipv4: boolean;
                ipv6: boolean;
                ftth: boolean;
            };
        };
        WanGraphPoint: {
            /** @description Unix timestamp (secondes) */
            ts: number;
            /** @description Débit en kbps */
            value: number;
        };
        WanGraphsData: {
            down: components["schemas"]["WanGraphPoint"][];
            up: components["schemas"]["WanGraphPoint"][];
        };
        CudyBandwidthPoint: {
            /** @description Unix timestamp (secondes) */
            ts: number;
            /** @description Débit montant en kbps */
            up: number;
            /** @description Débit descendant en kbps */
            down: number;
        };
        CudyBandwidthData: {
            /** @description Interface 2.4 GHz */
            ra0: components["schemas"]["CudyBandwidthPoint"][];
            /** @description Interface 5 GHz */
            rai0: components["schemas"]["CudyBandwidthPoint"][];
        };
        WanStatsSide: {
            bytes: number;
            bandwidth: number;
            contractualBandwidth: number;
            occupation: number;
        };
        WanStatsData: {
            rx: components["schemas"]["WanStatsSide"];
            tx: components["schemas"]["WanStatsSide"];
        };
        DhcpClient: {
            id: number;
            enable: number;
            hostname: string;
            macaddress: string;
            ipaddress: string;
            ip6address: string;
        };
        DhcpClientWrite: {
            enable: number;
            macaddress: string;
            ipaddress: string;
            ip6address: string;
            hostname: string;
        };
        DhcpConfig: {
            enable: number;
            minaddress: string;
            maxaddress: string;
            leasetime: number;
        };
        DhcpConfigUpdate: {
            enable?: number;
            minaddress?: string;
            maxaddress?: string;
            leasetime?: number;
        };
        DhcpClientsData: {
            clients: components["schemas"]["DhcpClient"][];
        };
        DhcpConfigData: {
            config: components["schemas"]["DhcpConfig"];
        };
        DhcpOption: {
            id: number;
            option: number;
            value: string;
        };
        DhcpOptionWrite: {
            option: number;
            value: string;
        };
        DhcpOptionCapability: {
            id: number;
            /** @enum {string} */
            type: "INT" | "IP" | "STRING" | "BOOL";
            description: string;
        };
        DhcpOptionsData: {
            options: components["schemas"]["DhcpOption"][];
            optionsstatic: components["schemas"]["DhcpOption"][];
            capabilities: components["schemas"]["DhcpOptionCapability"][];
        };
    };
    responses: never;
    parameters: {
        routerId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    checkIp: {
        parameters: {
            query: {
                ip: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Résultat du ping et de l'ARP */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckIpResponse"];
                };
            };
            /** @description Format d'IP invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    scanNetwork: {
        parameters: {
            query?: {
                /** @description CIDR à scanner (ex. 192.168.1.0/24). Détecté automatiquement si absent. */
                subnet?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flux SSE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getConfigRouters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouterEntry"][];
                };
            };
        };
    };
    getMapTopology: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapTopology"];
                };
            };
        };
    };
    getCudyStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        configured: number;
                        routers: {
                            name: string;
                            ip: string;
                        }[];
                    };
                };
            };
        };
    };
    getCudyWireless: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WirelessData"];
                };
            };
            /** @description Routeur introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCudyBandwidth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CudyBandwidthData"];
                };
            };
            /** @description Routeur introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBboxWireless: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WirelessData"];
                };
            };
        };
    };
    getHosts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostsData"];
                };
            };
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceData"];
                };
            };
        };
    };
    getWanStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WanStatsData"];
                };
            };
        };
    };
    getWanGraphs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WanGraphsData"];
                };
            };
        };
    };
    getDhcpConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DhcpConfigData"];
                };
            };
        };
    };
    updateDhcpConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpConfigUpdate"];
            };
        };
        responses: {
            /** @description OK */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDhcpClients: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DhcpClientsData"];
                };
            };
        };
    };
    createDhcpClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpClientWrite"];
            };
        };
        responses: {
            /** @description Créé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateDhcpClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpClientWrite"];
            };
        };
        responses: {
            /** @description OK */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDhcpClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDhcpOptions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DhcpOptionsData"];
                };
            };
        };
    };
    createDhcpOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpOptionWrite"];
            };
        };
        responses: {
            /** @description Créé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateDhcpOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpOptionWrite"];
            };
        };
        responses: {
            /** @description OK */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDhcpOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routerId: components["parameters"]["routerId"];
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
