/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/__health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État du serveur et de la session BBox */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__check-ip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifie si une IP est joignable et résout son adresse MAC */
        get: operations["checkIp"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/__scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Flux SSE de scan réseau
         * @description Retourne un flux Server-Sent Events. Événements émis :
         *     - `progress` — avancement du scan
         *     - `host` — hôte découvert (ping + MAC + vendor)
         *     - `host-detail` — détails d'un hôte (ports, ping stats, mDNS, SMB)
         *     - `done` — fin du scan
         *     - `error` — erreur fatale
         */
        get: operations["scanNetwork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bbox-api/api/v1/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Informations sur le routeur (modèle, firmware, uptime…) */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bbox-api/api/v1/wan/ip/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistiques de trafic WAN (débit, octets) */
        get: operations["getWanStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bbox-api/api/v1/wireless": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration Wi-Fi (SSID, canal, sécurité…) */
        get: operations["getWireless"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bbox-api/api/v1/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Appareils connectés au réseau local */
        get: operations["getHosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bbox-api/api/v1/dhcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration du serveur DHCP */
        get: operations["getDhcp"];
        /** Met à jour la configuration DHCP */
        put: operations["updateDhcp"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bbox-api/api/v1/dhcp/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des réservations DHCP statiques */
        get: operations["getDhcpClients"];
        put?: never;
        /** Crée une réservation DHCP */
        post: operations["createDhcpClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bbox-api/api/v1/dhcp/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Met à jour une réservation DHCP */
        put: operations["updateDhcpClient"];
        post?: never;
        /** Supprime une réservation DHCP */
        delete: operations["deleteDhcpClient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bbox-api/api/v1/dhcp/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des options DHCP configurées et disponibles */
        get: operations["getDhcpOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bbox-api/api/v1/dhcp/option": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crée une option DHCP */
        post: operations["createDhcpOption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bbox-api/api/v1/dhcp/options/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Met à jour une option DHCP */
        put: operations["updateDhcpOption"];
        post?: never;
        /** Supprime une option DHCP */
        delete: operations["deleteDhcpOption"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            ok: boolean;
            hasSession: boolean;
            /** @example https://mabbox.bytel.fr */
            target: string;
        };
        CheckIpResponse: {
            reachable: boolean;
            mac: string | null;
        };
        ScanProgress: {
            done: number;
            total: number;
        };
        ScanHost: {
            ip: string;
            mac: string;
            hostname: string;
            vendor: string;
            ping: boolean;
        };
        HostDetail: {
            ip: string;
            pingStats?: null | {
                min: number;
                avg: number;
                max: number;
            };
            openPorts: number[];
            mdnsName: string;
            smbName: string;
            smbDomain: string;
        };
        AnyObject: {
            [key: string]: unknown;
        };
        DhcpClient: {
            id: number;
            enable: number;
            hostname: string;
            macaddress: string;
            ipaddress: string;
            ip6address: string;
        };
        DhcpClientCreate: {
            enable: number;
            /** @description Alias du champ macaddress pour la création (contrainte API BBox) */
            device: string;
            ipaddress: string;
            ip6address: string;
            macaddress: string;
            hostname: string;
        };
        DhcpConfig: {
            enable: number;
            minaddress: string;
            maxaddress: string;
            leasetime: number;
        };
        DhcpConfigUpdate: {
            enable?: number;
            minaddress?: string;
            maxaddress?: string;
            leasetime?: number;
        };
        DhcpResponse: {
            dhcp: {
                state: number;
                enable: number;
                minaddress: string;
                maxaddress: string;
                leasetime: number;
            };
        };
        DhcpOption: {
            id: number;
            option: number;
            value: string;
        };
        DhcpOptionCreate: {
            option: number;
            value: string;
        };
        DhcpOptionUpdate: {
            enable: number;
            name: number;
            format: string;
            value: string;
        };
        DhcpOptionsResponse: {
            dhcp: {
                options: components["schemas"]["DhcpOption"][];
                optionsstatic: components["schemas"]["DhcpOption"][];
                optionscount: number;
                optionscapabilities: components["schemas"]["DhcpOptionCapability"][];
            };
        };
        DhcpOptionCapability: {
            id: number;
            /** @enum {string} */
            type: "INT" | "IP" | "STRING" | "BOOL";
            description: string;
            rfc: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    checkIp: {
        parameters: {
            query: {
                ip: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Résultat du ping et de l'ARP */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckIpResponse"];
                };
            };
            /** @description Format d'IP invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    scanNetwork: {
        parameters: {
            query?: {
                /** @description CIDR à scanner (ex. 192.168.1.0/24). Détecté automatiquement si absent. */
                subnet?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flux SSE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"][];
                };
            };
        };
    };
    getWanStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"][];
                };
            };
        };
    };
    getWireless: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"][];
                };
            };
        };
    };
    getHosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"][];
                };
            };
        };
    };
    getDhcp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DhcpResponse"][];
                };
            };
        };
    };
    updateDhcp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpConfigUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDhcpClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DhcpClient"][];
                };
            };
        };
    };
    createDhcpClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpClientCreate"];
            };
        };
        responses: {
            /** @description Créé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateDhcpClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpClientCreate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDhcpClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supprimé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDhcpOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DhcpOptionsResponse"][];
                };
            };
        };
    };
    createDhcpOption: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpOptionCreate"];
            };
        };
        responses: {
            /** @description Créé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateDhcpOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DhcpOptionUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDhcpOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supprimé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
